import React, { Component } from 'react';
import { withStyles } from '@material-ui/core/styles';
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography';
import Link from '@material-ui/core/Link';
import 'typeface-roboto';

const styles = theme => ({
  root: {
    width: '90%',
    marginTop: theme.spacing.unit * 3,
  },
  excerpt: {
    fontFamily: "Times New Roman"
  },
});

const posts = [
  ["Mayonnaise", "You'll never believe what Fred just did.  I'm telling you, I never thought someone could eat a whole bottle of mayonnaise like that but Fred, bless his heart, decided", "to give the mayonnaise a go.  - J.J. Abrams", "no comment"],
  ["Blue Paint", "I decided to cover my entire body in blue paint yesterday because I wanted to scare my son.  He's only a toddler, so when he saw me, he", "asked, 'Mom, why?'  I said, 'because I'm covering my whole body in paint, so you'll see what I really am.\nAs you can see from the picture, I'm wearing a green tutu and green and white polka dots.  I've painted my nails a light shade of blue, and I'm not covering my hair.", "no comment"],
  ["No Pants", "Now I know that taking off my pants in public was the wrong thing to do.  I definitely will not do it again; it was just that", "I just felt bad about my pants, and I'm sure I will never get caught by the cops again.  It was such a dumb decision that was way out of line but I wasn't thinking.  I do apologize to all of you.  And, I hve to mention that I don't believe in the 'just because you're drunk it doesn't mean you're able to get away with something.' I have to live my life every day with the knowledge that I'm lucky not to be in prison.  In any event, I think I've aid enough on the matter.  Now, as the time of my arrest draws near, I need to get the hell out of town and start my life over.  I don't know how much money I'll make by working in the", "no comment"]
]

class GPT2Blog extends Component {
  constructor(props) {
    super(props)

    this.state = {
      heading: "About",
      human: "This",
      machine: "text was generated by",
      comment: "yeah"
    }
  }

  setPost = (post) => {
    this.setState({
      heading: post[0],
      human: post[1],
      machine: post[2],
      comment: post[3]
    })
  }

  render () {
    const { classes } = this.props
    const { heading, human, machine, comment } = this.state

    return (
      <div className={classes.root}>
        <Grid container spacing={16} style={{ marginTop: "50px" }}>
          <Grid item xs={1} sm={1} style={{ background: "#FFFFFF", paddingLeft: "100px", paddingRight: "100px" }}>
            <br /> <br /> <br /> <br />
            <Typography className={classes.excerpt}>
              {posts.map((post, i) => [<Link onClick={() => this.setPost(post)}>{post[0]}</Link>, <br />])}
            </Typography>
          </Grid>
          <Grid item xs={8} sm={8}>
            <Typography variant='h2'>{heading}</Typography>
            <p className={classes.excerpt}><b>{human}</b> {machine}</p>
            <br /><br /><br />
            <Typography variant='p'><i>{comment}</i></Typography>
          </Grid>
        </Grid>

      </div>
    )
  }
}

export default withStyles(styles)(GPT2Blog);
